package com.any.mikuplushie.registry;

import com.any.mikuplushie.MikuPlushie;

/**
 * Since Minecraft 26.1 villager and wandering trader trades are data driven.
 * The trades of this mod are generated by {@link com.any.mikuplushie.datagen.ModDataJsonProvider}
 * into {@code data/miku-plushie/villager_trade} and added to the vanilla trade sets through
 * {@code data/minecraft/tags/villager_trade}.
 */
public class ModVillagerTrades {
    public static void initialize(){
        MikuPlushie.LOGGER.info(MikuPlushie.MOD_ID + " Villager Trades are data driven now");
    }
}
